Repository fridujo/rabbitmq-mock, pull requests merged in 2018-10, with the labels that each got.

#16 Add dead-letter-routing-key feature
  src/main/java/com/github/fridujo/rabbitmq/mock/AmqArguments.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
  src/test/java/com/github/fridujo/rabbitmq/mock/ExtensionTest.java
Labels: enhancement

#14 Upgrade versions
  pom.xml
  src/it/spring_boot/pom.xml
Labels: enhancement

#19 after queue shut down stop delivering more messages
  src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
  src/test/java/com/github/fridujo/rabbitmq/mock/IntegrationTest.java
Labels: bug

#20 Cancel consumers when closing connection
  src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
  src/test/java/com/github/fridujo/rabbitmq/mock/IntegrationTest.java
Labels: bug

#21 Support for version 5.4.3 of amqp-client
  README.md
  pom.xml
Labels: dependency upgrade
