Repository fridujo/rabbitmq-mock, pull requests merged in 2019-10, with the labels that each got.

#51 mark redelivered messages
  src/main/java/com/github/fridujo/rabbitmq/mock/Message.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
  src/test/java/com/github/fridujo/rabbitmq/mock/IntegrationTest.java
Labels: bug

#52 Fix consumer cancelation when another connection was closed
  src/it/alpakka/pom.xml
  src/it/alpakka/src/test/scala/com/github/fridujo/rabbitmq/mock/integration/alpakka/scala/TestSuite.scala
  src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockConnection.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
  src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
  src/test/java/com/github/fridujo/rabbitmq/mock/ComplexUseCasesTests.java
Labels: bug

#53 Upgrade amqp-client to latest (5.7.3)
  pom.xml
Labels: dependency upgrade

#54 (chore) Upgrade dev dependencies to latest
  pom.xml
Labels: dependency upgrade

#55 Add contributing guidelines
  CONTRIBUTING.md
Labels: enhancement

#56 Skip Integration Tests when tests are
  pom.xml
Labels: ecosystem
